canton {
  remote-participants {
    banka {
      admin-api {
        address = "canton"
        port = 5002
      }
      ledger-api {
        address = "canton"
        port = 5001
      }
    }

    bankb {
      admin-api {
        address = "canton"
        port = 5012
      }
      ledger-api {
        address = "canton"
        port = 5011
      }
    }

    bankc {
      admin-api {
        address = "canton"
        port = 5022
      }
      ledger-api {
        address = "canton"
        port = 5021
      }
    }

    synchronizer {
      admin-api {
        address = "canton"
        port = 5032
      }
      ledger-api {
        address = "canton"
        port = 5031
      }
    }
  }

  features.enable-preview-commands = yes
  features.enable-testing-commands = yes
  features.enable-repair-commands = yes
}