apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: fraudshield
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: fraudshield
  MONGO_INITDB_ROOT_PASSWORD: change-me-before-deploy
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fraudshield
type: Opaque
stringData:
  CORTEX_API_KEY: PASTE_YOUR_CORTEX_API_KEY_HERE
